### ISSUE TITLE
Incompatible with IE8.

### ISSUE THREAD

**Issue by neersighted** [rstone770/babelify-external-helpers#2]
This [line](https://github.com/rstone770/babelify-external-helpers/blob/master/source/module-rewriter.js#L15) (`var global = self = {}`) breaks in IE8, and appears to be unnecessary to the code. Is it possible to remove it or to replace it with something more compatible?

**Comment by neersighted** [comment]
`self` appears to be a reserved word, `var global = {}` works just as well.

**Comment by rstone770** [comment]
This is a typo.  It should define self via local scope. And you are right, its not needed.

**Comment by rstone770** [comment]
If you have some time, look over the proposed fix. If it works for you, ill merge it in.
